### ISSUE TITLE
Trying to see the other results

### ISSUE THREAD

**Issue by arighosh1** [jessye123/ab-ag-seq-machine-learning#1]
as per your paper, 2 nearest neighbor with string distance is 69% and 2 nearest neighbor with string distance and Levenshtein distance is 72%. Can you please tell me how to check those values? I could not find it in the code.

**Comment by jessye123** [comment]
you need to run python program in your computer and change the method for string calculation if you want to check it. This paper is still in progress.  and our team still working, the program are not final. Who are you? why you interest in this and want to check our paper in preprint stage?


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
From: arighosh1 ***@***.***>
Sent: Monday, 19 July 2021 12:40 PM
To: jessye123/ab-ag-seq-machine-learning ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jessye123/ab-ag-seq-machine-learning] Trying to see the other results (#1)


as per your paper, 2 nearest neighbor with string distance is 69% and 2 nearest neighbor with string distance and Levenshtein distance is 72%. Can you please tell me how to check those values? I could not find it in the code.
